import { reactive, computed } from 'vue';
import { FieldConfigManager, FieldDefinition, FieldGroup } from './fieldConfigManager';

// 导出 MMP 字段配置函数
export {
  createDoctorBasicInfoFieldConfig,
  createDoctorWorkExperienceFieldConfig,
  createDoctorQualificationCatalogFieldConfig,
  createDepartmentQualificationCatalogFieldConfig,
  createDoctorAbilityAssessmentFieldConfig,
  createDoctorAcademicPositionFieldConfig,
  createDoctorAdverseRecordFieldConfig,
  createDoctorCertificateFieldConfig,
  createDoctorEducationFieldConfig,
  createDoctorElectronicRegistrationFieldConfig,
  createDoctorEthicsEvaluationFieldConfig,
  createDoctorHonorFieldConfig,
  createDoctorInsuranceCodeFieldConfig,
  createDoctorPublicationFieldConfig,
  createDoctorResearchProjectFieldConfig,
  createDoctorTrainingFieldConfig,
  createQualificationAdmissionConditionFieldConfig,
  createQualificationAuthorizationApplyFieldConfig,
  createQualificationAuthorizationRecordFieldConfig,
  createQualificationExamArrangementFieldConfig,
  createQualificationExamPaperFieldConfig,
  createQualificationExamQuestionFieldConfig,
  createQualificationRiskMonitorFieldConfig,
  createQualificationUsageRecordFieldConfig,
  createTechnicianQualificationCatalogFieldConfig,
  createTumorQcIndicatorConfigFieldConfig,
  createTumorQcIndicatorDetailFieldConfig,
  createTumorQcIndicatorRecordFieldConfig,
  createSystemIndicatorMonitorRecordFieldConfig,
  createNewTechnologyExtensionApplyFieldConfig,
  createNewTechnologyMappingFieldConfig,
  createNewTechnologyProgressReportFieldConfig,
  createNewTechnologyProjectFieldConfig,
  createNewTechnologyCaseFieldConfig,
  createNewTechnologyCatalogFieldConfig,
  createAnnouncementFieldConfig,
  createSurgeryRecordFieldConfig,
  createSurgeryComplicationRecordFieldConfig,
  createSurgeryTeamFieldConfig,
  createComplaintDisputeFieldConfig
} from './mmpFieldConfigs';
